[package]
name = "thaler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-std = "0.4.0"
ndarray = "0.16.1"
rand = "0.8"
